//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPAftercare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AftercareEntities : DbContext
    {
        public AftercareEntities()
            : base("name=AftercareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblChild> tblChilds { get; set; }
        public virtual DbSet<tblParent> tblParents { get; set; }
        public virtual DbSet<tblParentChild> tblParentChilds { get; set; }
        public virtual DbSet<tblUpload> tblUploads { get; set; }
        public virtual DbSet<tblExpense> tblExpenses { get; set; }
        public virtual DbSet<tblIncome> tblIncomes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
