//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPAftercare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpense
    {
        public int ExpID { get; set; }
        public int UserID { get; set; }
        public string ExpAmount { get; set; }
        public string expDesc { get; set; }
        public System.DateTime expDate { get; set; }
        public string expRemarks { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
