//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPAftercare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIncome
    {
        public int IncID { get; set; }
        public int UserID { get; set; }
        public string incAmount { get; set; }
        public string incDesc { get; set; }
        public System.DateTime incDate { get; set; }
        public string incRemarks { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
