//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPAftercare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class tblUpload
    {
        public int UploadID { get; set; }

        [DisplayName("File Name")]
        public string fileName { get; set; }

        [DisplayName("File Preview")]
        public string filePath { get; set; }
    }
}
